
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "minerslunchbox"
  description = "Lunchbox, yum"
  version = "1.0.0+mc1.18.2"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/Nova-Committee/MinersLunchbox"
  author = "pkstDev"

# These are global requirements
[requirements]
  minecraft = "1.18.2"
  fabricLoader = ">=0.14.6"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"

  [dev.dependencies]
    test-mansion = "*"
